[package]
name = "uget"
version = "0.1.0"
edition = "2021"
authors = ["Rogerio Ara√∫jo <rogerio.araujo@gmail.com>"]
repository = "https://github.com/ararog/deboa"
homepage = "https://github.com/ararog/deboa"
description = "A minimal cli tool to make http requests. You want, you get!"
readme = "README.md"
license = "MIT"
keywords = ["http", "networking", "client", "fetch", "rest"]
publish = true
rust-version = "1.70.0"

[dependencies]
assert_cmd = "2.0.13"
clap = { version = "4.5.51", features = ["derive"] }
colored = "2.2.0"
colored_json = "5.0.0"
deboa = { path = "../../deboa", version = "0.0.7" }
futures-util = "0.3.31"
http = "1.3.1"
http-body-util = "0.1.3"
indicatif = "0.18.0"
mime = "0.3.17"
tokio = { version = "1.47.2", features = ["full"] }
url = "2.5.7"
